name: FormHandler

on:
  push:
    branches: [ "main" ] # Asegúrate de que coincida con tu rama predeterminada

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # CAMBIO CLAVE: Apunta directamente a la carpeta de tu HTML 
          # Nota: Usa el nombre exacto respetando mayúsculas (ej: 'frontend' o 'Frontend')
          path: 'frontend'

      - name: FormHandler
        id: deployment
        uses: actions/deploy-pages@v4
